# url: https://coreaiteam.github.io
# baseurl: /agency-jekyll-theme

# Site settings
title: 4M Team
email: coreaiteam2025@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: محمد تسلیمی
  pic: 1
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mohammad-taslimi/
    - title: github
      url: https://github.com/MoTa2380


- name: محمدمهدی نوروزی
  pic: 2
  social:
    - title: linkedin
      url: #
    - title: github
      url: #

- name: محمدجواد نوروزی
  pic: 3
  social:
    - title: linkedin
      url: #
    - title: github
      url: #

- name: محمدحسین مومنی
  pic: 4
  social:
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty